-- 고양이와 개는 몇 마리 있을까
SELECT ANIMAL_TYPE, COUNT(ANIMAL_TYPE) as 'count' FROM ANIMAL_INS
GROUP BY ANIMAL_TYPE ORDER BY ANIMAL_TYPE ASC;

-- 동명 동물 수 찾기
SELECT NAME, COUNT(NAME) as 'COUNT' FROM ANIMAL_INS
WHERE NAME IS NOT NULL GROUP BY NAME HAVING COUNT(NAME) >= 2
ORDER BY NAME ASC;

-- 입양 시각 구하기 (1)
SELECT HOUR(DATETIME) AS HOUR, COUNT(DATETIME) AS COUNT FROM ANIMAL_OUTS
GROUP BY HOUR HAVING HOUR >= 9 AND HOUR <= 19 ORDER BY HOUR ASC;